version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:80"
  worker:
    build: .
    entrypoint: ["dotnet", "Worker.dll"]
  db:
    image: mysql:8.0
    volumes:
      - "jobalert_db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  jobalert_db:
