version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - "db"
  worker:
    build: .
    entrypoint: ["dotnet", "Worker.dll"]
    depends_on:
      - "db"
  
  migrate:
    image: migrate/migrate
    volumes:
      - './migrations:/migrations'
    # command: ["-path", "/migrations", "-database",  "mysql://root:secret@tcp(db:3306)/jobalert", "up", "3"]
    command: ["-path", "/migrations", "-database",  "mysql://root:secret@tcp(db:3306)/jobalert", "down", "--y"]
    depends_on: 
      - "db"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - "jobalert_db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "jobalert"
volumes:
  jobalert_db:
