version: '3.9'
services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - "db"
    environment:
      - "ConnectionStrings__Default=server=db;uid=root;pwd=${DB_PASSWORD:-secret};database=${DB_DATABASE:-jobalert};allow user variables=true;"

  worker:
    build: .
    entrypoint: ["dotnet", "Worker.dll"]
    depends_on:
      - "db"
    environment:
      - "ConnectionStrings__Default=server=db;uid=root;pwd=${DB_PASSWORD:-secret};database=${DB_DATABASE:-jobalert};allow user variables=true;"
  
  migrate:
    image: migrate/migrate
    volumes:
      - './migrations:/migrations'
    command: ["-path", "/migrations", "-database",  "mysql://root:${DB_PASSWORD:-secret}@tcp(db:${DB_PORT:-3306})/${DB_DATABASE:-jobalert}", "up"]
    depends_on: 
      - "db"
    profiles:
      - migrate

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - "jobalert_db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
      MYSQL_DATABASE: '${DB_DATABASE:-jobalert}'
volumes:
  jobalert_db:
