#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    # Proxy Migrate commands to the "migrate" binary on the application container...
    if [ "$1" == "migrate" ]; then
        shift 1

        docker-compose exec \
            migrate \
            migrate --help
    fi


else
    docker-compose ps
fi
